"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bn4(ksye_!p0l_h23dd+o02py7rok(2k3c6xivm#1cf2psvpq9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',       # admin site — see todos/admin.py, accounts/admin.py
    'django.contrib.auth',        # User model + authentication — see accounts app
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',             # Django REST Framework — see todos/api
    'accounts',                   # signup/login/logout
    'todos',                      # Project/Task domain models, views, API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Uploaded RAG documents (see todos/models.py:Document). Deliberately not
# wired into config/urls.py — see todos/rag.py's module docstring for why
# uploaded files are never served back over a public URL.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/models/fields/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Where django.contrib.auth.decorators.login_required sends anonymous users,
# and where a successful login redirects to. Paired with accounts/urls.py.
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'todos:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Password reset emails print to the console instead of actually sending —
# there's no real mail server in this learning project. Swap for
# smtp.EmailBackend (or a provider like SES/SendGrid) in production.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# OpenRouter powers the "Generate with AI" description helper (see todos/ai.py).
# OPENROUTER_MODEL is tried first; if it's rate-limited, ai.py falls back to
# each model in OPENROUTER_FALLBACK_MODELS in order.
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = 'inclusionai/ling-3.0-flash:free'
OPENROUTER_FALLBACK_MODELS = ['google/gemini-3.5-flash-lite']

# Powers document-upload RAG (see todos/rag.py) — embeds document chunks at
# upload time and the user's message at query time, via the same
# OpenRouter account/key as the chat completions above.
OPENROUTER_EMBEDDING_MODEL = 'openai/text-embedding-3-small'

REST_FRAMEWORK = {
    # Every API view requires a logged-in user unless it says otherwise.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Session auth reuses the same login the browsable UI uses; convenient for
    # learning purposes so you can browse /api/ while logged into the site.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}
